### API Requests for Patient Management System

# Create a new patient
# Sends a POST request to create a new patient record.
# The request body must contain the patient's name, email, address, date of birth, and registration date.
POST http://localhost:4000/patients/
Content-Type: application/json

{
  "name": "Carlos Torres WITH BILLING ACCOUNTs",
  "email": "carTori_billing_accountsss@gmail.com",
  "address": "343 La Paz",
  "dateOfBirth": "1999-10-02",
  "registeredDate": "2025-03-22"
}
###